[phases.setup]
nixPkgs = [
    "nodejs_20",
    "pnpm-8_x",       # Install pnpm v8 directly
    "openssl",
    "vips",
    "glib",
    "expat",
    "libjpeg",
    "libpng",
    "libtiff"
]

[phases.install]
commands = [
    # Bypass Corepack completely
    "npm uninstall -g corepack",
    # Use pnpm directly from Nix store
    "pnpm install --frozen-lockfile"
]

[phases.build]
commands = [
    "pnpx prisma generate --schema=./cdw/prisma/schema/schema.prisma",
    "pnpm run build"
]

[phases.start]
command = "pnpm start"