[phases.setup]
nixPkgs = [
    "nodejs_20",       # Explicit Node.js 20 installation
    "pnpm_8",        # Ensure pnpm is available
    "openssl",
    "vips",            # Required for sharp
    "glib",
    "expat",
    "libjpeg",
    "libpng",
    "libtiff"
]

[phases.install]
commands = [
    "corepack enable",  # Use system corepack
    "pnpm install --frozen-lockfile"
]

[phases.build]
commands = [
    "pnpx prisma generate",
    "pnpm run build"
]

[phases.start]
command = "pnpm start"