[phases.setup]
nixPkgs = [
    "nodejs_20",
    "pnpm-8_x",
    "openssl",
    "vips",
    "glib",
    "expat",
    "libjpeg",
    "libpng",
    "libtiff"
]

[phases.install]
commands = [
    "npm uninstall -g corepack",
    "npm install -g pnpm@8.15.7",
    "ls -la",  # Keep this for diagnostics
    "pnpm install --no-frozen-lockfile"
]

[phases.build]
commands = [
    # Corrected Prisma path - removed cdw/ since it doesn't exist
    "pnpx prisma generate",
    "pnpm run build"
]

[phases.start]
command = "pnpm start"