[phases.setup]
nixPkgs = [
    "nodejs_20",        # Explicit Node.js 20 installation
    "pnpm-8_x",         # Correct pnpm v8 package name
    "openssl",
    "vips",             # Required for sharp
    "glib",
    "expat",
    "libjpeg",
    "libpng",
    "libtiff"
]

[phases.install]
commands = [
    "corepack enable",  # Use system corepack
    "pnpm install --frozen-lockfile"
]

[phases.build]
commands = [
    "pnpx prisma generate --schema=./cdw/prisma/schema/schema.prisma",
    "pnpm run build"
]

[phases.start]
command = "pnpm start"