[phases.setup]
nixPkgs = [
    "nodejs_20",
    "pnpm-8_x",       # Install pnpm v8 directly
    "openssl",
    "vips",           # Required for image processing
    "glib",
    "expat",
    "libjpeg",
    "libpng",
    "libtiff"
]

[phases.install]
commands = [
    "npm uninstall -g corepack",  # Remove problematic corepack
    "npm install -g pnpm@8.15.7", # Install specific pnpm version
    "ls -la",                    # Diagnostic: list files
    "ls -la cdw/",               # Verify project structure
    "pnpm install --no-frozen-lockfile"  # Flexible dependency installation
]

[phases.build]
commands = [
    "pnpx prisma generate --schema=./cdw/prisma/schema/schema.prisma",
    "pnpm run build"
]

[phases.start]
command = "pnpm start"

[environment]
PNPM_DISABLE_COREPACK = "1"  # Ensure corepack doesn't interfere